spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aula-1?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC&sessionVariables=sql_mode=''
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/aula-1?serverTimezone=UTC&createDatabaseIfNotExist=true
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDB103Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update